/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    InstrumentDetails: typeof import('./src/components/InstrumentDetails.vue')['default']
    MusicDetails: typeof import('./src/components/MusicDetails.vue')['default']
    MusicionDetails: typeof import('./src/components/MusicionDetails.vue')['default']
    MyNavigation: typeof import('./src/components/MyNavigation.vue')['default']
    MyPoem: typeof import('./src/components/MyPoem.vue')['default']
    NewInstrument: typeof import('./src/components/NewInstrument.vue')['default']
    NewMusic: typeof import('./src/components/NewMusic.vue')['default']
    NewMusician: typeof import('./src/components/NewMusician.vue')['default']
    NewSearch: typeof import('./src/components/NewSearch.vue')['default']
    PoemDetails: typeof import('./src/components/PoemDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
